### ISSUE TITLE
[IMP] Adding subtasks in exercise 001

### ISSUE THREAD

**Issue by zeina99** [gimseng/99-ML-Learning-Projects#71]
Since this repo is aimed at people trying to learn machine learning, I think it would be helpful if subtasks were added in exercise 001, especially in regards to data analysis and feature engineering.

Like for example:
- data analysis
    - plot the survival rate of males and females 
    - Survival rate based on age
    - etc..
    - finally, what observations do you make of the analysis?
- feature engineering
    - dealing with missing values
    - dealing with categorical values
    - etc..
- building the model
    - choose a model
    - fit the data
    - get the accuracy metrics
    - **bonus**: test on multiple models and compare accuracy

Since it can be a little overwhelming at the start, providing some sort of outline could be helpful.
If the above steps are too specific, it could be a little more broad to allow the person to think by themselves.

A bonus section could also be added, for those who want to go the extra mile.

**Comment by gimseng** [comment]
@zeina99 Great idea ! I think expanding on the `readme.md` to include detailed subtask is fantastic !

At the practical level, would you be interested in working on this? I presume that we should update the exercise description in `readme.md` first. Then, we should accordingly update the solution to reflect on how it addresses each task. If you want to work not the solution (both the code and the `readme.md`) that would be great too. Otherwise we can leave that for others to grab.

Thanks !

**Comment by zeina99** [comment]
I would be glad to work on both!

@gimseng Would you want the tasks to match the steps done in the solution, so that it's somewhat similar? or would be better to just add tasks and then fix up the solution to match the tasks?
