### ISSUE TITLE
[IMP] Add Pytorch solutions

### ISSUE THREAD

**Issue by Syn-Tax** [gimseng/99-ML-Learning-Projects#73]
Expanding on issue #26 it may be worth adding multiple solutions written using both tf/keras and pytorch. I would be happy to work on solutions to current exercises.

**Comment by gimseng** [comment]
@Syn-Tax Great ! Please go ahead and proceed as you see fit. One organization comment: Since we already organize the current 2 solutions as `titanic_classical` and `titanic_tf_nn` it might make sense for you to create a notebook named `titanic_pt_nn` or something to that effect, and then update the `readme.md`. 

Thanks and look forward to your contribution !
